[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nodejs"]

[phases.install]
cmds = ["COMPOSER_ALLOW_SUPERUSER=1 composer install --optimize-autoloader --no-interaction"]

[phases.build]
cmds = ["COMPOSER_ALLOW_SUPERUSER=1 composer dump-autoload --optimize --no-interaction"]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public"